### ISSUE TITLE
How to override style defaults

### ISSUE THREAD

**Issue by kccmcck** [mike-engel/floating-label-react#3]
I'd like to make some modifications to the default styles, but have not figured out a way to do so without making use of `!important` in my component's css file.

For example, how would I go about changing `paddingTop: 5` in `labelStyles` to `paddingTop: 0`?

**Comment by mike-engel** [comment]
Hi @kccmcck! `floating-label-react` takes a `styles` prop, which is an object of objects of styles. You should be able to override that like so:

```js
<FloatingLabel styles={{ label: { paddingTop: 0 } }} />
```

There seems to be, however, a bug where the `labelStyles` will always override the custom values, as seen here: https://github.com/mike-engel/floating-label-react/blob/bd4dbdf34e1c5f6ca00f4dffe358949bff44b1e4/index.js#L81

I'm not sure how much time I'll have to dedicate to this immediately. If you'd like to make a PR I'd be happy to review and merge it!

**Comment by mike-engel** [comment]
I just published version `0.2.0`, which should fix the issue above. Let me know if you still have trouble.
