### ISSUE TITLE
[Need Help] Regarding Extracting value from input Box

### ISSUE THREAD

**Issue by pavanmehta91** [mike-engel/floating-label-react#5]
Is it a controlled component like I'd have a normal input text? I don't see props.value been assigned in the 
`<Node>` declaration?

**Comment by mike-engel** [comment]
@pavanmehta91 It is not strictly a controlled component. `props.value` is assigned to the `Node` component through the `defaultValue` prop, which makes it an uncontrolled component. You would then pass an `onChange` function to update your local state to the new value. If you still have questions, let me know!

**Comment by pavanmehta91** [comment]
No I think I'd have to use defaultValue if I want to prefill the fields. Thanks for a quick response though 👍
