### ISSUE TITLE
Style textarea

### ISSUE THREAD

**Issue by guayom** [mike-engel/floating-label-react#6]
Hi! I was trying out this plugin and it's very cool.
I can't style the textarea though, how do you do that?

**Comment by mike-engel** [comment]
@guayom It's part of the `input` style. Usage documentation is here, at the bottom for style stuff: https://github.com/mike-engel/floating-label-react#usage. And then here is where new styles are passed in: https://github.com/mike-engel/floating-label-react/blob/6aa2dc65771ae6008e34fa0ea1cecb33208198af/index.js#L120

**Comment by guayom** [comment]
Thanks, you're right, I forgot to pass the styles to the textarea! Ugh, so silly
